# Generated by Django 5.2.17 on 2026-10-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True, choices=[("male", "Nam"), ("female", "Nữ")], max_length=10
            ),
        ),
    ]
