# Generated by Django 5.2.17 on 2026-10-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_profile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name="profile",
            name="birth_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="hometown",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
