# Generated by Django 5.2.17 on 2026-10-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_outboxevent_connection_conversation_costscenario_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['low', 'active'], name='core_connec_low_id_5427cd_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['high', 'active'], name='core_connec_high_id_6194ce_idx'),
        ),
        migrations.AddIndex(
            model_name='connectionrequest',
            index=models.Index(fields=['recipient', 'status'], name='core_connec_recipie_d57554_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['profile', 'created_at'], name='core_notifi_profile_10ad7f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['profile', 'read', 'created_at'], name='core_notifi_profile_40563d_idx'),
        ),
        migrations.AddIndex(
            model_name='swipedecision',
            index=models.Index(fields=['actor', 'choice', 'updated_at'], name='core_swiped_actor_i_d91a75_idx'),
        ),
        migrations.AddIndex(
            model_name='swipedecision',
            index=models.Index(fields=['target', 'choice', 'updated_at'], name='core_swiped_target__50481e_idx'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['target', 'actor'], name='core_userbl_target__a78315_idx'),
        ),
    ]
