# Generated by Django 5.2.17 on 2026-10-05 08:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_connection_core_connec_low_id_5427cd_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='connectionrequest',
            index=models.Index(fields=['sender', 'status'], name='core_connec_sender__aafd12_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['is_published', 'is_synthetic'], name='core_profil_is_publ_861aab_idx'),
        ),
    ]
