# Generated by Django 5.2.17 on 2026-10-03 08:32

import django.db.models.deletion
import journey.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_lifestyle_survey_2026_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.JSONField(default=list)),
                ('title', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=250)),
                ('delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('generation', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_high', to='core.profile')),
                ('low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_low', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='journey.connection')),
            ],
        ),
        migrations.CreateModel(
            name='CostScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_version', models.PositiveIntegerField()),
                ('weights', models.JSONField(default=dict)),
                ('calculation', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=4)),
                ('previous_choice', models.CharField(blank=True, max_length=4)),
                ('undone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_events', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='LivingPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_in_from', models.DateField(blank=True, null=True)),
                ('move_in_until', models.DateField(blank=True, null=True)),
                ('needs', models.CharField(blank=True, max_length=500)),
                ('sleep_at', models.TimeField(blank=True, null=True)),
                ('wake_at', models.TimeField(blank=True, null=True)),
                ('quiet_from', models.TimeField(blank=True, null=True)),
                ('quiet_until', models.TimeField(blank=True, null=True)),
                ('total_monthly_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('upfront_budget', models.PositiveIntegerField(blank=True, null=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='living', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(default=uuid.uuid4)),
                ('body', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='journey.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='MutationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('key', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.profile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.outboxevent')),
            ],
        ),
        migrations.CreateModel(
            name='PinnedFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='journey.conversation')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.message')),
            ],
        ),
        migrations.CreateModel(
            name='FactConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='journey.pinnedfact')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, max_length=3000)),
                ('version', models.PositiveIntegerField(default=1)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_about', to='core.profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_notes', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1000)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to='core.profile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RoomChoiceProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_version', models.PositiveIntegerField()),
                ('member_version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.costscenario')),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='journey.roomchoiceproposal')),
            ],
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.FileField(storage=journey.models.PrivateStorage(), upload_to=journey.models.private_image_path)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ImagePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('question', models.CharField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='journey.roomimage')),
            ],
        ),
        migrations.CreateModel(
            name='RoomOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('notes', models.TextField(blank=True, max_length=3000)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_options', to='core.profile')),
                ('source_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journey.roomoption')),
            ],
        ),
        migrations.CreateModel(
            name='RoomOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('interested', 'Quan tâm'), ('unsure', 'Chưa chắc'), ('no', 'Không phù hợp')], max_length=12)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('version', models.PositiveIntegerField(default=1)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opinions', to='journey.roomoption')),
            ],
        ),
        migrations.AddField(
            model_name='roomimage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='journey.roomoption'),
        ),
        migrations.CreateModel(
            name='RoomCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('period', models.CharField(choices=[('monthly', 'Hàng tháng'), ('initial', 'Đầu kỳ / một lần'), ('deposit', 'Tiền cọc')], max_length=10)),
                ('state', models.CharField(choices=[('unknown', 'Chưa biết'), ('estimated', 'Ước tính'), ('known', 'Đã biết')], default='unknown', max_length=10)),
                ('amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=250)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='journey.roomoption')),
            ],
        ),
        migrations.AddField(
            model_name='roomchoiceproposal',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey.roomoption'),
        ),
        migrations.AddField(
            model_name='costscenario',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='journey.roomoption'),
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('done', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='journey.roomoption')),
            ],
        ),
        migrations.CreateModel(
            name='SavedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='core.profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_candidates', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SearchWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Cùng tìm nơi muốn về', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Chờ đồng ý'), ('active', 'Cùng tìm'), ('declined', 'Đã từ chối'), ('closed', 'Đã kết thúc')], default='pending', max_length=10)),
                ('member_version', models.PositiveIntegerField(default=1)),
                ('moving_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='journey.conversation')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_received', to='core.profile')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_invitations', to='core.profile')),
            ],
        ),
        migrations.AddField(
            model_name='roomoption',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='journey.searchworkspace'),
        ),
        migrations.AddField(
            model_name='roomchoiceproposal',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='journey.searchworkspace'),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journey.searchworkspace'),
        ),
        migrations.CreateModel(
            name='MoveInTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='journey.searchworkspace')),
            ],
        ),
        migrations.CreateModel(
            name='JourneyCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint', to='core.profile')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journey.searchworkspace')),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clauses', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('member_version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journey.roomchoiceproposal')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='journey.searchworkspace')),
            ],
        ),
        migrations.CreateModel(
            name='SwipeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('like', 'Muốn kết nối'), ('pass', 'Bỏ qua')], max_length=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='core.profile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_swipes', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.profile')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to='core.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ViewingEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journey.roomimage')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='journey.roomoption')),
            ],
        ),
        migrations.CreateModel(
            name='ViewingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField()),
                ('meeting_point', models.CharField(blank=True, max_length=250)),
                ('version', models.PositiveIntegerField(default=1)),
                ('cancelled', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewings', to='journey.roomoption')),
            ],
        ),
        migrations.CreateModel(
            name='ViewingResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('accepted', models.BooleanField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='journey.viewingplan')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='core.profile')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='journey.searchworkspace')),
            ],
        ),
        migrations.CreateModel(
            name='AgreementConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='journey.agreement')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('agreement', 'member', 'version'), name='journey_unique_agreement_consent')],
            },
        ),
        migrations.CreateModel(
            name='ClauseResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('key', models.CharField(max_length=30)),
                ('accepted', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='journey.agreement')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('agreement', 'member', 'version', 'key'), name='journey_unique_clause_response')],
            },
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(fields=('low', 'high'), name='journey_unique_pair'),
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.CheckConstraint(condition=models.Q(('low__lt', models.F('high'))), name='journey_ordered_pair'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('connection', 'generation'), name='journey_unique_conversation'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'sender', 'client_id'), name='journey_unique_message'),
        ),
        migrations.AddConstraint(
            model_name='mutationreceipt',
            constraint=models.UniqueConstraint(fields=('actor', 'action', 'key'), name='journey_unique_mutation'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('event', 'profile'), name='journey_unique_notification'),
        ),
        migrations.AddConstraint(
            model_name='factconsent',
            constraint=models.UniqueConstraint(fields=('fact', 'member', 'version'), name='journey_unique_fact_consent'),
        ),
        migrations.AddConstraint(
            model_name='privatenote',
            constraint=models.UniqueConstraint(fields=('owner', 'candidate'), name='journey_unique_note'),
        ),
        migrations.AddConstraint(
            model_name='choiceconsent',
            constraint=models.UniqueConstraint(fields=('proposal', 'member'), name='journey_unique_choice_consent'),
        ),
        migrations.AddConstraint(
            model_name='imagepin',
            constraint=models.CheckConstraint(condition=models.Q(('x__gte', 0), ('x__lte', 1), ('y__gte', 0), ('y__lte', 1)), name='journey_pin_bounds'),
        ),
        migrations.AddConstraint(
            model_name='roomopinion',
            constraint=models.UniqueConstraint(fields=('room', 'member'), name='journey_unique_room_opinion'),
        ),
        migrations.AddConstraint(
            model_name='roomcost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount__isnull', True), ('state', 'unknown')), models.Q(('amount__isnull', False), ('state__in', ['estimated', 'known'])), _connector='OR'), name='journey_cost_state_amount'),
        ),
        migrations.AddConstraint(
            model_name='savedcandidate',
            constraint=models.UniqueConstraint(fields=('owner', 'candidate'), name='journey_unique_saved'),
        ),
        migrations.AddConstraint(
            model_name='searchworkspace',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active'])), fields=('conversation',), name='journey_one_open_workspace'),
        ),
        migrations.AddConstraint(
            model_name='swipedecision',
            constraint=models.UniqueConstraint(fields=('actor', 'target'), name='journey_unique_swipe'),
        ),
        migrations.AddConstraint(
            model_name='swipedecision',
            constraint=models.CheckConstraint(condition=models.Q(('actor', models.F('target')), _negated=True), name='journey_no_self_swipe'),
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.UniqueConstraint(fields=('actor', 'target'), name='journey_unique_block'),
        ),
        migrations.AddConstraint(
            model_name='viewingresponse',
            constraint=models.UniqueConstraint(fields=('plan', 'member', 'version'), name='journey_unique_viewing_response'),
        ),
        migrations.AddConstraint(
            model_name='workspacemember',
            constraint=models.UniqueConstraint(fields=('workspace', 'profile'), name='journey_unique_member'),
        ),
    ]
