# Generated by Django 5.2.17 on 2026-10-04 09:04

import django.db.models.deletion
from django.db import migrations, models


def populate_recipient_index(apps, schema_editor):
    Event = apps.get_model('journey', 'OutboxEvent')
    Recipient = apps.get_model('journey', 'OutboxRecipient')
    Profile = apps.get_model('core', 'Profile')
    alias = schema_editor.connection.alias
    for event in Event.objects.using(alias).only('pk', 'recipients').iterator(chunk_size=500):
        ids = {value for value in event.recipients if type(value) is int and value > 0}
        existing = Profile.objects.using(alias).filter(pk__in=ids).values_list('pk', flat=True)
        Recipient.objects.using(alias).bulk_create(
            [Recipient(event_id=event.pk, profile_id=value) for value in existing], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auth_rate_bucket'),
        ('journey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='delivery_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='outboxevent',
            name='retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='OutboxRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_links', to='journey.outboxevent')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'profile'), name='journey_unique_outbox_recipient')],
            },
        ),
        migrations.RunPython(populate_recipient_index, migrations.RunPython.noop),
    ]
