"""Central re-export module for all web views (maintaining backward compatibility)."""

from core.web.account import (
    dashboard,
    delete_avatar,
    login_view,
    logout_view,
    profile_edit,
    questionnaire,
    register,
    upload_avatar,
)
from core.web.actions import action, notifications, perform, resume
from core.web.chat import chat, hub, messages, pair_messages
from core.web.discovery import (
    candidate,
    candidate_card,
    candidate_rows,
    compare_candidates,
    modern_discover,
    preferences,
    saved,
)
from core.web.legacy_discovery import (
    blocked_pair,
    comparison,
    connect,
    connection_action,
    discover,
    ensure_user_profile_for_discovery,
    find_matches,
    overlap,
)
from core.web.pilot import pilot_exercise, pilot_export, pilot_results
from core.web.public import about
from core.web.workspace import (
    agreement,
    choice_context,
    compare_rooms,
    edit_room,
    image,
    opinions_for_room,
    room,
    room_calculation,
    room_cost_overview,
    rooms,
    workspace,
)

__all__ = [
    "about",
    "register",
    "login_view",
    "logout_view",
    "dashboard",
    "profile_edit",
    "upload_avatar",
    "delete_avatar",
    "questionnaire",
    "candidate_card",
    "candidate_rows",
    "modern_discover",
    "candidate",
    "saved",
    "compare_candidates",
    "preferences",
    "choice_context",
    "room_cost_overview",
    "workspace",
    "rooms",
    "edit_room",
    "room_calculation",
    "opinions_for_room",
    "room",
    "compare_rooms",
    "image",
    "agreement",
    "notifications",
    "resume",
    "perform",
    "action",
    "chat",
    "hub",
    "messages",
    "pair_messages",
    "pilot_exercise",
    "pilot_results",
    "pilot_export",
    "discover",
    "comparison",
    "connect",
    "connection_action",
    "find_matches",
    "overlap",
    "blocked_pair",
    "ensure_user_profile_for_discovery",
]
